//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class Travel_HubEntities : DbContext
    {
        private static Travel_HubEntities _context;
        public Travel_HubEntities()
            : base("name=Travel_HubEntities")
        {
        }

        public static Travel_HubEntities GetContext()
        {
            if (_context == null)
            {
                _context = new Travel_HubEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Бронирование> Бронирование { get; set; }
        public virtual DbSet<Бронирование_Номер> Бронирование_Номер { get; set; }
        public virtual DbSet<Вид_номера> Вид_номера { get; set; }
        public virtual DbSet<Данные_пользователя> Данные_пользователя { get; set; }
        public virtual DbSet<Номер> Номер { get; set; }
        public virtual DbSet<Офис> Офис { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<Роль_пользователя> Роль_пользователя { get; set; }
        public virtual DbSet<Статус_бронирования> Статус_бронирования { get; set; }
    }
}
