//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Бронирование
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Бронирование()
        {
            this.Бронирование_Номер = new HashSet<Бронирование_Номер>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_пользователя { get; set; }
        public Nullable<int> Статус_заказа { get; set; }
        public Nullable<int> ID_офиса { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Бронирование_Номер> Бронирование_Номер { get; set; }
        public virtual Офис Офис { get; set; }
        public virtual Пользователь Пользователь { get; set; }
        public virtual Статус_бронирования Статус_бронирования { get; set; }
    }
}
