//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Бронирование_Номер
    {
        public int ID { get; set; }
        public Nullable<int> ID_бронирования { get; set; }
        public Nullable<int> ID_номера { get; set; }
    
        public virtual Бронирование Бронирование { get; set; }
        public virtual Номер Номер { get; set; }
    }
}
