//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Номер
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Номер()
        {
            this.Бронирование_Номер = new HashSet<Бронирование_Номер>();
        }
    
        public int ID { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> Вид_номера { get; set; }
        public Nullable<System.DateTime> Даты { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public byte[] Изображение { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Бронирование_Номер> Бронирование_Номер { get; set; }
        public virtual Вид_номера Вид_номера1 { get; set; }
    }
}
